services:
  # Backend API
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - minio
    networks:
      - comicif-network

  # Frontend (placeholder for future)
  # frontend:
  #   build:
  #     context: ./apps/frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./apps/frontend:/app
  #     - /app/node_modules
  #   networks:
  #     - comicif-network

  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: comicif
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - comicif-network

  # Object Storage
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - comicif-network

volumes:
  postgres_data:
  minio_data:

networks:
  comicif-network:
    driver: bridge